In [2]:
print("Hello world")

Hello world


In [3]:
x=10
y=30
course="Data visualization"
print(x,y,course)

10 30 Data visualization


In [5]:
# Control Flow statement
x=0

if x>0:
  print("Positive")
elif x==0:
  print("zero")
else:
  print("Negative")

zero


In [7]:
#Looping

for i in range(1,10):
  print(i)

1
2
3
4
5
6
7
8
9


In [8]:
fruits=["apple","mango","banana"]

for i in fruits:
  print("I like", i)

I like apple
I like mango
I like banana


In [11]:
#while
count =1
while count<=5:
  print(count)
  count=count+1

1
2
3
4
5


In [66]:
#break and continue

for i in range(1,10):
  if i==5:
    break
  print(i)

1
2
3
4


In [68]:
  for i in range(1,10):
    if i==5:
      continue
    print(i)

1
2
3
4
6
7
8
9


In [16]:
#defining function
def add(a,b):
  return a+b

In [17]:
print(add(4,5))

9


In [18]:
#Numpy

import numpy as np

In [19]:
#create array

arr= np.array([1,2,3,4,5,6,7,8,9])

print(arr)

[1 2 3 4 5 6 7 8 9]


In [20]:
max_value=np.max(arr)
min_value=np.min(arr)

In [21]:
print(max_value)
print(min_value)

9
1


In [22]:
#Matrix

matrix1= np.array([[1,2],[3,4]])
print(matrix1)

[[1 2]
 [3 4]]


In [23]:
#Random Matrix

random_matrix=np.random.rand(5,6)
print(random_matrix)

[[0.15049432 0.90544375 0.97304488 0.00163138 0.86339153 0.48624815]
 [0.39010513 0.96323864 0.05392446 0.09679911 0.6931962  0.13666692]
 [0.83064977 0.97939359 0.59601917 0.35842648 0.71937706 0.49675579]
 [0.06153167 0.6971336  0.25917911 0.85997524 0.19489356 0.66102548]
 [0.68429523 0.19591721 0.05238217 0.66600271 0.95503661 0.92949659]]


In [25]:
new_row =np.random.rand(1,6)
print(new_row)

[[0.46753288 0.7312611  0.16950451 0.26866594 0.29332181 0.90834033]]


In [ ]:
random_matrix=np.hstack([random_matrix,new_row])

In [29]:
random_integer=np.random.randint(0,100, size=(5,6))

In [30]:
print(random_integer)

[[37  8 82 50 57 58]
 [46  9 30 77 29 56]
 [46 64 71 58 53  3]
 [99 75 74 66  1 19]
 [33 70 61 59 91  2]]


In [31]:
#Pandas library

import pandas as pd

In [69]:
df1= pd.read_csv("/content/iris.csv")
df2=pd.read_csv("/content/Student.csv")

In [71]:
print(df2)

  Name  Age  Marks
0    A   20     80
1    B   21     87
2    C   22     56
3    D   23     45
4    E   24     34
5    F   22     78


In [38]:
#Head
print(df.head(10))

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa
5           5.4          3.9           1.7          0.4  Setosa
6           4.6          3.4           1.4          0.3  Setosa
7           5.0          3.4           1.5          0.2  Setosa
8           4.4          2.9           1.4          0.2  Setosa
9           4.9          3.1           1.5          0.1  Setosa


In [39]:
#Head
print(df.tail(10))

     sepal.length  sepal.width  petal.length  petal.width    variety
140           6.7          3.1           5.6          2.4  Virginica
141           6.9          3.1           5.1          2.3  Virginica
142           5.8          2.7           5.1          1.9  Virginica
143           6.8          3.2           5.9          2.3  Virginica
144           6.7          3.3           5.7          2.5  Virginica
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica


In [40]:
df.describe()

sepal.length  sepal.width  petal.length  petal.width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [41]:
print(df.shape)

(150, 5)


In [42]:
print(df.size)

750


In [43]:
# Columns

print(df.columns)

Index(['sepal.length', 'sepal.width', 'petal.length', 'petal.width',
       'variety'],
      dtype='object')


In [72]:
sepal_variety=df[["sepal.length","variety"]]

In [74]:
petal_variety=df[["petal.length","variety"]]

In [75]:
petal_variety

petal.length    variety
0             1.4     Setosa
1             1.4     Setosa
2             1.3     Setosa
3             1.5     Setosa
4             1.4     Setosa
..            ...        ...
145           5.2  Virginica
146           5.0  Virginica
147           5.2  Virginica
148           5.4  Virginica
149           5.1  Virginica

[150 rows x 2 columns]

In [76]:
sepal_variety

sepal.length    variety
0             5.1     Setosa
1             4.9     Setosa
2             4.7     Setosa
3             4.6     Setosa
4             5.0     Setosa
..            ...        ...
145           6.7  Virginica
146           6.3  Virginica
147           6.5  Virginica
148           6.2  Virginica
149           5.9  Virginica

[150 rows x 2 columns]

In [46]:
#datatypes of the columns

print(df.dtypes)

sepal.length    float64
sepal.width     float64
petal.length    float64
petal.width     float64
variety          object
dtype: object


In [53]:
#check for missing values

print(df.isnull().sum())

sepal.length    0
sepal.width     0
petal.length    0
petal.width     0
variety         0
dtype: int64


In [54]:
#check for missing values

print(df.isnull().sum())

sepal.length    0
sepal.width     0
petal.length    0
petal.width     0
variety         0
dtype: int64


In [55]:
#SLicing

features_array=df.iloc[:,0:4].values

In [56]:
print(features_array)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [62]:
mean=np.mean(features_array,axis=0)
print(mean)
median=np.median(features_array,axis=0)
print(median)

[5.84333333 3.05733333 3.758      1.19933333]
[5.8  3.   4.35 1.3 ]


In [64]:
#correlation matrix

correlation_matrix= np.corrcoef(features_array.T)
print(correlation_matrix)

[[ 1.         -0.11756978  0.87175378  0.81794113]
 [-0.11756978  1.         -0.4284401  -0.36612593]
 [ 0.87175378 -0.4284401   1.          0.96286543]
 [ 0.81794113 -0.36612593  0.96286543  1.        ]]


In [ ]:
   A B C D
 A 1
 B   1
 C     1
 D       1